name: humble_sand
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  get_it: ^7.2.0
  intl: ^0.17.0
  intl_utils: ^2.6.1
  shared_preferences: ^2.0.13
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.14
  flutter_svg: ^1.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
